[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[logger]
hideWelcomeMessage = true

[server]
showEmailPrompt = false

[theme.sidebar]
backgroundColor = "#192638"
textColor = "#FFFFFF"
secondaryBackgroundColor = "#24344D"
primaryColor = "#FF0000"
